### ISSUE TITLE
Softpatching not working

### ISSUE THREAD

**Issue by ValiumBear** [libretro/Mesen#11]
Using latest core update, I've tried with 2 games that previously used to work fine but now it gives no notice of loading the patches at all. 
I've tested the other NES cores and they load them automatically.
I thought it might be iNES/NES header issue, but that's not it either.
Standalone Mesen loads the patches automatically too without issue.

Let me know if you can reproduce it.
Edit: Good news, 1.9.4 stable works as expected. So it's a recent commit and should be easier to track down.

**Comment by i30817** [comment]
I'm not certain, but it might be because of this project: https://github.com/libretro/RetroArch/issues/12949

Which sets this cores setting 'need_fullpath = false' to false. 

Presumably the idea is for RA itself to provide streams and cores not access files directly (for various reasons).

So then it would be good if the cores softpatching support was moved to the frontend so it still worked.

edit: actually, i just tested it and it's probably that Mesen and FCEUmm just don't support .bps. Ips works fine, bps is ignored.

**Comment by ValiumBear** [comment]
Just tested IPS on latest Retroarch and seems to work fine now. Issue solved.

**Comment by Sanaki** [comment]
RetroArch's softpatching supports ips, bps, and ups by the way. If your bps didn't patch, you probably have a checksum mismatch.

**Comment by i30817** [comment]
I actually did, but i solved it when converting because applying the bps was the only way to convert to ips. I thought it was because bps wasn't supported in the NES cores but i didn't verify the original bps with the right rom on retroarch, just applied it and converted to ips with flips, but i can easily see a mismatch happening.  @ValiumBear 

Also as a aside if bps fails because of a crc mismatch maybe it would be better for that to be signaled with a notification instead of failing silently because of this, which just makes people think that particular cores don't support bps instead of the wrong rom being used.

EDIT: confirmed, the patch i was trying with the right rom applies and without fails silently.

btw @ValiumBear, if you're trying to apply the Megami Tensei II translation, the news article forum link on romhacking has a way to turn a older rom into the new one, or you could get the one on the internet archive by following the nointro release name on google.
